server:
  port: 1111
  context-path: /girl

girl:
  cupSize: F
  age: 18
  context: "cupSize: ${cupSize}, age: ${age}"


eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false