server:
  port: 1111
  context-path: /girl

girl:
  cupSize: F
  age: 18
  context: "cupSize: ${cupSize}, age: ${age}"

spring:
  application:
    name: hello-service

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/girl/

